<?php

return
[
	'page_direction' => 'ltr',
	'page_direction' => 'rtl',
	'STUDY' => 'STUDY',
	'ENGLISH' => 'ENGLISH',
	'united_kingdomh' => 'United Kingdom',
	'united_states_of_americah' => 'United States of America',
	'canadah' => 'Canada',
	'australiah' => 'Australia',
	'new_zealandh' => 'New Zealand',
	'south_africah' => 'South Africa',
	'maltah' => 'Malta',
	'irelandh' => 'Ireland',
	'united_kingdom' => 'There is no better place to study English than in the UK. England is an ancient and beautiful country brimming with history, home of Shakespeare and the Royal Family. In addition to its cultural heritage the UK is also one of the most cosmopolitan and vibrant countries on earth. You will enjoy the experience of a lifetime when you take an English course in England.',
	'united_states_of_america' => 'From the buzz of the Big Apple and the historic grandeur of Boston on the East Coast to the laidback beach vibe of San Diego and the myriad attractions of San Francisco/Berkeley on the West Coast, it offers you many options to study English in the USA. From Broadway shows in New York to historical walking tours in Boston, from surfing in San Diego to visits to Alcatraz and Sausalito at San Francisco/Berkeley, the schools social program provides a perfect complement to your English course in the USA.',
	'canada' => 'If you want to learn English in a cosmopolitan and vibrant city but also want to study in an environment that is safe, green and friendly with easy access to some of the world’s most spectacular scenery, then you want to study English in Canada, and offer a fun and varied social program designed to complement your English course in Canada by getting the most out of this stunning country.',
	'australia' => 'English is the universal business language and Australia is home to the finest education system in the world that teaches English. Australia is known for employing top-caliber instructors to meet the needs of students studying abroad and to ensure the level of English Proficiency is at par if not above global standards. Studying English in Australia offers wide-range courses to suit your study needs from Academics, Work Opportunities, General English Studies, English for Teaching, Travel Purposes and Examination Preparation',
	'new_zealand' => 'Learn English in Auckland and explore the world-famous natural beauty of New Zealand. And from here you can enjoy trips to museums, beaches, famous lakes, and mountains. Auckland is perfect for adventure lovers. Abseil from the Sky Tower; plunge down waterfalls in the Coromandel rainforests, or go whale-watching between the islands of the Hauraki Gulf. Choose Auckland English school for an experience you will remember forever.',
	'south_africa' => 'With the majestic Table Mountain nestled in the background and the sea all around, Cape Town is an awe-inspiring city filled with natural beauty. Learn English in Cape Town, surf, hike, or cycle after your lessons and use your new language skills to explore the culinary scene that Cape Town is famous for. South Africa’s “Mother City” is incredibly diverse, with old and new cultures coming together to make something unique and spectacular.',
	'malta' => 'Learn English in Malta, a charming, friendly country that boasts three UNESCO World Heritage sites, a lively nightlife scene, and sunny days that will make this English language Experience one you’ll remember for years to come.',
	'ireland' => 'Dublin is an amazing city and the capital of Ireland. It has a rich cultural tradition, having been home to many famous writers and poets and has been the setting for some of the most famous novels in the world and makes for an inspiring place to learn English with history all around you! Dublin is exciting in the present, too – it’s Europe’s techno hub and is home to companies like Facebook and Google.',
	'kaplan_international_languages' => 'Kaplan International Languages is a division of education company Kaplan Inc., headquartered in London. Kaplan International Languages provides English courses, as well as French and German courses after acquiring Alpadia Language Schools in 2019. Kaplan International Languages offer a wide range of courses, including intensive language programs, exam preparation courses and programs for juniors at locations in the UK, Ireland, USA, Canada, Australia, New Zealand, France, Germany, Switzerland and Spain.',
	'lal_language_center' => 'With more than 30 years of experience, LAL Language Centres is a pioneer of global language travel, dedicated to providing the very best language learning opportunities for adults and young learner students from over 100 countries.  LAL combines first-class language education, teacher training, unrivalled leisure options and the very best support services in a selection of beautiful and stimulating destinations.  Our teachers are skilled at tailoring our lessons to make them engaging and dynamic while meeting the needs of each student.',
	'into' => 'Prepare for study, work and life in an English-speaking country with one of INTO’s English language courses. The courses run throughout the year, and you will be taught by experienced and supportive tutors.
			From scenic towns to vibrant cities, INTO can help you improve your English in a world-class university location in either the UK or US. You’ll practice your new skills with native English speakers, make new friends from all over the world, and experience the local culture in every way possible.',
	'kings_education' => 'Kings Education is a specialist and a high-quality international education group. They specialize in university pathways and English language teaching in the US and UK – the two most established and popular destinations for international study. They also partnered with select, quality schools in China, Malaysia and Albania.',
	'ec' => 'EC is a chain of English language schools based in Malta. The school acquired its first overseas school in Brighton. EC Brighton, a great school in a great location, was quickly followed by EC Cambridge and then EC London (in the city’s prestigious Covent Garden area). EC ventured outside Europe in 2006 with the establishment of EC Cape Town and then opened three American schools: EC Boston, EC San Diego and EC New York. This year EC’s 1200-plus staff will help over 40,000 students from over 120 countries to learn and improve their English language skills. Their vision is to maintain our growth while helping students from all over the world succeed in a global community.',
	'regent' => 'Regent was one of the first groups of English language schools in the UK. It was established over 50 years ago in 1964 by a passionate, experienced teacher who wanted to found a proper school, with proper teachers and proper courses. Today Regent offers innovative courses in a choice of academically and culturally rich locations that create life changing opportunities for our students.',
	'bsc' => 'The Companys origins date back to the 1930s when it was founded by the Cleaver family. In the early days British Study Centres (BSC) concentrated on correspondence courses and as such was a precursor to the Open University which grew up in the 1960s. The Company grew quickly, establishing offices and examination centres across the entire (then) British Empire and beyond and in the process becoming the UKs largest group of correspondence colleges. Today, BSC specializes in the delivery of high quality English language training to adults and young learners, teacher training courses for UK and overseas teachers and University Pathway Programmes in partnership with NCUK; a consortium of leading UK universities.',
	'bell' => 'For over 60 years, we have provided unforgettable learning experiences to students and teachers from around the world, transforming the lives of over one million people. Through our teaching approach, The Bell Way, we encourage you to aim high, exceed your learning goals and become a confident user of the English language. Bell was founded by Frank Bell, a University of Cambridge graduate, with a love of languages and a vision to promote intercultural understanding through language education. This led him, in 1955, to open his first language school in Cambridge, which still operates today.',
	'stafford_house' => 'Stafford House International is a group of English language schools that offer courses for general, academic and professional purposes. Our mission is to educate, inspire, and help our students enjoy our cities, empowering them with confidence, to realize their personal potential. Our schools are located in 10 fantastic American, Canadian and British cities that each offer a unique way to improve your language and we’d like to invite you on a learning adventure. All ten of our schools have been designed to the highest specifications. You will learn in fresh and bright classrooms, with up-to-date learning technology and modern conveniences, including IT suites, high-speed WiFi, comfortable student lounges and cafes.',
	'st_giles' => 'Every year around 10,000 students from over 100 different countries choose St Giles for their language and learning needs. Established in 1955, we offer 65 years experience in providing excellence in training for people of all ages, all needs, and from all over the world. Reasons to choose us is because we have 65 years experience teaching English, an international reputation for high-quality teaching, choice of locations in the UK, the USA, Canada, flexible programs designed for a range of ages, abilities, and objectives, a personal learning experience, with a focus on you and your needs, exciting, fast-paced, and learner-centered lessons, modern teaching centers offering the latest resources, excellent value for money.',
	'celtic_english_academy' => 'We are a welcoming English language academy with friendly and helpful teachers and staff. We first opened as Celtic School in 2004 and have been welcoming students from all over the world since then. This means we have a lot of expertise in providing students with a quality study experience. Our excellent core teaching team is complemented by our academic and office support teams. These teams ensure the smooth day-to-day running of our friendly and welcoming English academy. From Celtic School to Celtic English Academy, we have changed a lot, but our values have remained the same. We nurture minds through education not only in language but culture and respect with our values.',
	'eurocenter' => 'With over 70 years of experience in language teaching, Eurocentres is committed to providing services of the highest standards at schools all over the world. Studying at an officially-accredited language centre under the guidance of highly-qualified teachers and dedicated industry advisors, you can be sure that your learning journey is in safe hands. Eurocentres was born in 1948 as a way to transform learning into an enriching, personal experience. Since then, we have evolved into a market leader in international language teaching, with schools across Europe, the USA, and Canada, as well as in New Zealand, South Africa, and Australia.',
	'lsi'  => 'LSI has an extensive network of schools located around the world . You can learn English in one of our schools in England, Canada, the USA, New Zealand or Australia. We also have language centres in France and Switzerland. LSI also works with partner language schools in Spain, Italy, Mexico, Panama and Costa Rica. All our schools are modern and equipped with the latest technology. They are in the centre of attractive city destinations. LSI teachers possess solid teaching skills and all staff have been carefully selected to ensure a friendly and helpful service can be extended to all LSI students. They are on hand to guide you through your studies.',
	'twin' => 'Welcome to Twin! We are an accredited provider of English tuition, and a work experience and group tour provider, trusted by students, parents, and agents around the world. Founded in 1993, we have successfully developed a broad range of English courses, work placement opportunities and group travel services for students from the UK and overseas. Our English schools in Greenwich, Eastbourne, and Dublin have standard and tailor-made programs, offering great value for money, whether you are looking for courses or accommodation options to suit your needs.',
	'ces' => 'Founded in 1979, CES has over 40 years experience teaching the English language to students from across the globe. In Ireland, all of our teachers hold a university degree plus an ACELS recognized teaching qualification, with many holding specialist EFL teaching qualifications, such as DELTA, our teachers are chosen not only for their experience but also for their enthusiasm, positive attitude and their ability to make language learning fun.',
	
	
];